### ISSUE TITLE
AttributeError in pyomo.core.base.component.pprint (possible regression when upgrading IDEAS from v1.7 to 1.9)

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/idaes-pse#250]
Posting this from on behalf of the original reporter from an email thread:

I’ve been trying to update to the latest release of IDAES (v1.9). I had been running with v1.7.

I think I mostly figured out how to upgrade IDAES to v1.9, but now I’m having some trouble getting previous IDAES models to run with the new version (both my own models and earlier sample models that ran in v1.7). Some of the errors I’m getting are relatively straightforward and should be easy to fix (I’m bypassing them for now), but now I’m consistently getting an error from deeper in the Pyomo code and I don’t know how to fix it. I was wondering if one of you could help me figure out what the issue is. The last error message that is sent to the console is this:

```txt
File "C:\Users\Mike\AppData\Local\conda\conda\envs\idaes-pse\lib\site-packages\pyomo\core\base\component.py", line 502, in pprint

self.is_constructed(), *self._pprint()

AttributeError: 'AMPLExternalFunction' object has no attribute '_pprint'
```
 

My python code that triggers this is the first line of my model code where I’m first trying to add an object (a simple turbine using a PressureChanger) to my model:

```py
    m.fs.hp_turb = PressureChanger(
        default={
            "property_package": m.fs.prop_water,
            "compressor": False,
            "thermodynamic_assumption": ThermodynamicAssumption.isentropic,
        }
    )
```

**Comment by lbianchi-lbl** [comment]
@andrewlee94 @jghouse88: @dangunter suggested you might have some comments on this.

**Comment by MikeErbes** [comment]
I'm the original poster (Mike Erbes from Enginomix). I figured out that after updating IDAES (following the update instructions, which said to use "pip install --upgrade idaes-pse", the new version of IDAES was installed in different locations than the previous version (at least the main folders). I was trying to run python scripts that were in the previous version folders, but those won't run without modification. I found the new sample python scripts in the new IDAES location, and the sample models stored there will run. So I started modifying my own model scripts to run with the new version, and am running into different issues. Some of them I can work through on my own (some of the unit models have been renamed and/or moved, etc.), but others I'm not sure what's going on.  In my previous model (I was running IDAES 1.7) these lines of code were used to set the inlet conditions to the steam cycle:

    pin = 12.2e6  # 1769 psia
    tin = 810.9   # 1000 F
    hin = iapws95.htpx(T=tin, P=pin)
    m.fs.valve.inlet.enth_mol.fix(hin)**

But this code generates the following errors:

 File "C:\Users\Mike\AppData\Local\conda\conda\envs\idaes-pse\lib\site-packages\pyomo\core\base\units_container.py", line 1330, in convert
    'Error in convert: units not compatible.')

InconsistentUnitsError: Error in convert: units not compatible.: dimensionless not compatible with kelvin.

Following the code written in the new versions of the sample model, I can use the following code instead, which will run without error:

    pin = 12.2e6  # 1769 psia
    #tin = 810.9   # 1000 F
    #hin = iapws95.htpx(T=tin, P=pin)
    hin = 61958
    m.fs.valve.inlet.enth_mol.fix(hin)

But it is inconvenient to have to specify the enthalpy. I tried using pyomo units of measure, but could not get those to work. When I try the following (with the appropriate import command added):

    pin = 12.2e6*pyunits.Pa  # 1769 psia
    tin = 810.9*pyunits.K
    hin = iapws95.htpx(T=tin, P=pin)
    m.fs.valve.inlet.enth_mol.fix(hin)

We get an error message from the solver:

 File "C:\Users\Mike\AppData\Local\conda\conda\envs\idaes-pse\lib\site-packages\pyomo\opt\base\solvers.py", line 602, in solve
    "Solver (%s) did not exit normally" % self.name)

ApplicationError: Solver (ipopt) did not exit normally

Any help would be appreciated. Thanks.

**Comment by ksbeattie** [comment]
@MikeErbes, hmmm, the new version shouldn't have been installed into a different folder than the old version.  Can you show the different folders the versions were installed into?

I think we might want to update our upgrade instructions to prefer using an entirely new conda environment from a previous version.  What we've got there *should* work, but it would be cleaner to start in a new conda env.  Could you try that and see if you are still seeing the same problem?  Here's the steps:

Create and activate a new Conda env:

    conda create --name idaes-pse-1.9.0 python=3.7 -y
    conda activate idaes-pse-1.9.0

Install using either (but only one) of the following commands:

    pip install idaes-pse
    conda install -c IDAES-PSE -c conda-forge idaes-pse

Then install the packaged solvers:

    idaes get-extensions  # Windows and Linux only

Note that this can be done from any dir and should not changes any files in the current dir.  That way you should be able to keep one dir of your code and switch between verisons of idaes-pse by changing conda envs with `conda deactivate/activate` commands.

**Comment by andrewlee94** [comment]
@MikeErbes 

For the first error (the one @lbianchi-lbl posted), we would need to see more of the error to know what is happening (i.e. the full error traceback). Something strange is happening in the Pyomo code, but I have no idea what it might be from that final output. I did do a quick check of the Pyomo code to see where the failure was happening, and I did note that the line number in your error output did not line up with the current version of Pyomo - it would be worth checking that you have the correct version of Pyomo installed.

For the second error (regarding units), your fix to add units to the `htpx` function is correct, and that appears to have worked (the problem was passed to the solver). However, something happened in the solver step which resulted in a solver failure (not even an infeasible solution). For this, the first thing to do is to look at the solver output, which depends on whether the solver failure is occurring during initialization or during a solver call you wrote.

1. If the failure is occurring during initialization, first `import idaes.logger as idaeslog` and the add `outlvl=idaeslog.DEBUG` to the initialization call (i.e. `model.initialize(outlvl=idaeslog.DEBUG)`.
2. If this is occurring during your own solver call, add `tee=True` to the solver call, i.e. `solver.solve(model, tee=True)`.

This will show you what the solver is doing and maybe give some insight into what the issue is.

**Comment by MikeErbes** [comment]
@ksbeattie 
I'm not that familiar with these environments (python, anaconda, etc.), so much of this is new for me. I installed the first version (IDAES v1.7) following instructions provided as part of a seminar or tutorial that Rodney Gay sent us (it was titled "Tutorial 1 05/08/2020 - Install Demo speaker notes"). To upgrade to the latest version (IDAES v1.9), I poked around on the documentation site and found the instructions for upgrading and followed those. 

During my first install (v1.7) this was the folder where the IDAES files wound up ("Mike" being my user name on that PC):
   C:\Users\Mike\anaconda3\envs\idaes-pse\Lib\site-packages\idaes
For the upgrade to v1.9, I followed the instructions I found online and the IDAES folders wound up here:
   C:\Users\Mike\AppData\Local\conda\conda\envs\idaes-pse\Lib\site-packages\idaes

I generally have been using Spyder to write and debug my python IDAES models. What happened after upgrading to v1.9 was that I opened Spyder and it automatically opened all the python files from the previous install (including some of the standard sample models such as supercritical_steam_cycle). I then just tried to run them, and immediately ran into the problems I mentioned previously, even with the sample models (because Spyder had opened the sample models from the old version). So all of these old models were being run with the newly installed IDAES v1.9. I realize now that the python model files need to modified to run with v1.9 due to changes in the underlying IDAES code. I figured out where the old and new directory folders were, and then found that I could run the updated example files (such as supercritical_steam_cycle) without error, so I started modifying my own python model files to work with the new version. That's where I am now. 

I spoke with Rodney yesterday and he told me that he has several different conda environments for different versions of IDAES. Not because he'd figured that out on his own, but because someone at one of the IDAES meetings he attended in the past set things up for him that way on his PC at the meeting. In hindsight, that is something I should have done, but I didn't realize there would be significant issues running models built in v1.7 under v1.9, and that it was possible to have multiple, parallel versions installed.  Based on my experience with this, I would definitely recommend that the upgrade instructions recommend this as standard procedure, so you can continue to run your existing models with previous versions. 

I should maybe mention that one of the reasons I didn't think to try and install a parallel version of IDAES, besides the fact that I didn't see it mentioned in the upgrade instructions, is that I am used to working with (and developing) commercial process simulation packages where we do everything possible to make sure that old models will run with newer versions of the software. I've been responsible for and involved in the development of commercial packages such as GateCycle and IPSEpro (since 1988). With both of those packages, we can pretty much open any older models with any newer version of the software (if any changes to the files are required, we try to minimize them and document them for the user, or sometimes we build tools to convert model files). This backwards compatibility is a key requirement for commercial software like this, so I've gotten used to thinking that all process simulation software is like this. IDAES is apparently not quite at this stage of development yet, so I should have realized I might have trouble running my old models in the newer versions. You probably should mention that in the upgrade instructions and recommend that people keep the old versions installed in parallel with the new version, in particular so they can continue to run their old models. I would also recommend that you put together a list of things users need to change in their python model files when upgrading from one version to another. I'm still in the process of figuring that out, how to upgrade my IDAES v1.7 model files to run with v1.9.

**Comment by MikeErbes** [comment]
@andrewlee94 

I played around a bit with the code for the valve inlet conditions, and I found that the issue seems to be when I assign units to the pressure variable, pin. I haven't dug into the documentation on pyomo units of measure (I was just following examples I saw in other sample code), but if I change the code that was working before to the following:

    pin = 12.2e6*pyunits.Pa  # 1769 psia
    #tin = 810.9   # 1000 F
    #hin = iapws95.htpx(T=tin, P=pin)
    hin = 62112.37
    m.fs.valve.inlet.enth_mol.fix(hin)

I then get the same solver errors. So just adding *pyunits.Pa to the variable pin is what's causing the problem. That variable i only used in one more place after this in the code a few lines below, namely:

    m.fs.valve.inlet.pressure.fix(pin)

So it must be that call that is causing the solver issues. 

I'll try to look into the logging and the solver errors next week when I have some more time to look into this.

**Comment by andrewlee94** [comment]
@MikeErbes Ahh.. I see your problem, and I hope I will explain it properly. The issue comes when you do:

`m.fs.valve.inlet.pressure.fix(pin)`

The issue is that Pyomo expects `pin` to be a `float`, but it doesn't actually check this. In this case, `pin = 12.2e6*pyunits.Pa` which is a Pyomo expression. Pyomo naively assigns this to the value of the variable, which then causes solver issues later as it does not know what to do with the expression. On a side note, the `units` of a variable are assigned and recorded separately from the `value`.

So, what you need to do is only provide the units part when you are using the `htpx` function. When you go to `fix` a variable value, you need to use only the float part.

Also note that the `htpx` function is units aware, and you can actually pass values in other units if you wish, as shown below:

```
hin = iapws95.htpx(T=1000*pyunits.degF, P=1769*pyunits.psi)
m.fs.valve.inlet.enth_mol.fix(hin)
```

When it comes to fixing the value for pressure however, you need to provide a value in the correct units, which you can do as shown:

```
pin_Pa = pyunits.convert_value(1769, from_units=pyunits.psi, to_units=pyunits.Pa)
m.fs.valve.inlet.pressure.fix(pin_Pa)
```

**Comment by jsiirola** [comment]
This is related to Pyomo/pyomo#1431
