### PR TITLE
Require Click version 8 or greater

### LINKED ISSUE #696: Error when running `idaes` commands: TypeError: __init__() got an unexpected keyword argument 'package_name'
Originally reported by @elbashandy, this issue can occur when running any of the `idaes` commands from the command line:

```sh
$ idaes get_extensions
Traceback (most recent call last):
  File "C:\Users\aaelbashandy\.conda\envs\idaes\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\aaelbashandy\.conda\envs\idaes\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\aaelbashandy\.conda\envs\idaes\Scripts\idaes.exe\__main__.py", line 4, in <module>
  File "C:\Users\aaelbashandy\.conda\envs\idaes\lib\site-packages\idaes\commands\__init__.py", line 18, in <module>
    from idaes.commands.base import command_base as cb
  File "C:\Users\aaelbashandy\.conda\envs\idaes\lib\site-packages\idaes\commands\base.py", line 79, in <module>
    def command_base(verbose, quiet):
  File "C:\Users\aaelbashandy\.conda\envs\idaes\lib\site-packages\click\decorators.py", line 304, in decorator
    return option(*(param_decls or ("--version",)), **attrs)(f)
  File "C:\Users\aaelbashandy\.conda\envs\idaes\lib\site-packages\click\decorators.py", line 192, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "C:\Users\aaelbashandy\.conda\envs\idaes\lib\site-packages\click\core.py", line 1714, in __init__
    Parameter.__init__(self, param_decls, type=type, **attrs)
TypeError: __init__() got an unexpected keyword argument 'package_name'
```

The cause for this is likely that the installed version of `click` is not compatible with the `package_name` option, introduced in Click 8.0. To verify this, run `pip show click`.

A quick solution is to update the installed version of `click`, e.g. by running `pip install click==8`.

### PR DESCRIPTION
**Pull request by lbianchi-lbl**
## Summary/Motivation:

- The changes introduced in #683 turned out to be not backwards-compatible with Click 7 and below, so we should specify Click 8 as the minimum version

## Changes proposed in this PR:
- Add version constraint for Click version 8 or greater

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by lbianchi-lbl** [comment]
Since the changes in this PR cannot affect the outcome of the CI checks (the same version of Click would have been installed in a fresh environment regardless of the constraint being added), I' m going ahead and merge this.
